/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-key */
import Head from 'next/head';
import styles from '../../styles/Home.module.css'
import { useQuery } from '@apollo/client'
import { Grid, Box, Paper, experimentalStyled as styled, Card, CardActionArea, CardContent, CardMedia, Typography, FormGroup, FormControlLabel, List, ListItem, IconButton, ListItemAvatar, Avatar, ListItemText, Container } from '@mui/material';
import InfoIcon from '@mui/icons-material/Info';
import Image from 'next/image';
import { withApollo } from '../../lib/apollo/client';
import NavTabs from '../../components/navbar';
import { useRouter } from 'next/router';
import DeleteIcon from '@mui/icons-material/Delete';
import { useEffect, useState } from 'react';

const Item = styled(Paper)(({ theme }) => ({
    ...theme.typography.body2,
    padding: theme.spacing(2),
    textAlign: "center",
    color: theme.palette.text.secondary
}));

const Cart = () => {
    const [cart, setCart] = useState([]);
    let total = 0

    useEffect(() => {
        let cart = localStorage.getItem('cart');
        if (cart !== undefined) {
            if (cart === null) {
                setCart([])
            } else {
                let result = JSON.parse(cart) || [];
                setCart(result)
            }
        }

    }, [])

    cart.map(i => {
        total += i.price_range.maximum_price.final_price.value
    })
    return (
        <div className={styles.container}>
            <NavTabs />
            <Head>
                <title>Mini E-Commerce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h3 className={styles.title}>
                    List Cart
                </h3>
                <Box sx={{ flexGrow: 3, marginTop: 3}}>
            <Container maxWidth="xl">
                <List sx={{ width: '100%', maxWidth: 360, bgcolor: 'rgba(120, 183, 228, 0.1)', borderRadius: 2}}>
      {cart.map((i, index) => (
        <ListItem
          key={index}
          disableGutters
          secondaryAction={
            <IconButton>
              <DeleteIcon />
            </IconButton>
          }
        >
        <Avatar src={i.image.url} style={{marginLeft: 10}}/>
          <ListItemText 
          primary={i.name} 
          style={{marginLeft: 10}} />
        </ListItem>
      ))}
      <h3>Total : {total}</h3>
    </List>
    </Container>
    </Box>
            </main>

            <footer className={styles.footer}>
                <span className={styles.logo}>
                    Created by Restiani Andhita Mustikasari
                </span>
            </footer>
        </div>
    )
}

export default withApollo({ ssr: true })(Cart);
