/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/jsx-key */
import Head from 'next/head';
import styles from '../../styles/Home.module.css'
import { useQuery } from '@apollo/client'
import {GET_CATEGORIES} from './service/schema'
import { Grid, Box, Paper, experimentalStyled as styled, Card, CardActionArea, CardContent, CardMedia, Typography } from '@mui/material';
import InfoIcon from '@mui/icons-material/Info';
import Image from 'next/image';
import { withApollo } from '../../lib/apollo/client';
import NavTabs from '../../components/navbar';
import Link from 'next/link';

const Item = styled(Paper)(({ theme }) => ({
    ...theme.typography.body2,
    padding: theme.spacing(2),
    textAlign: "center",
    color: theme.palette.text.secondary
  }));

const Category = () => {
    const { loading, error, data } = useQuery (GET_CATEGORIES);
    if (error || loading ) return<></>;
    const {mainCategories} = data;
    const {items} = mainCategories;
  return (
    <div className={styles.container}>
    <NavTabs />
      <Head>
        <title>Mini E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <h3 className={styles.title}>
         Our Category
        </h3>

        <Box sx={{flexGrow:2}} style={{paddingTop:30}}>
        <Grid container spacing={{xs:2, md:3}} columns={{xs:4, sm:8, md:12}}>
        {items.map((i, index) =>(
            <Grid item xs={4} sm={4} md={4} key={index}>
            <Link as={`/categories/${i.name}`} href={`/categories/${i.name}`}>
            <Item style={{backgroundColor:'rgba(253, 254, 255, 0.7)', fontWeight:'bold'}} elevation={6}>
            <Card sx={{maxWidth: '100%'}}>
            <CardActionArea>
                    <CardMedia
                    component="img" height="140"
                    image={i.image}
                    alt={i.name}
                    />
                    <CardContent>
                    <Typography gutterBottom variant="h5" component="div">
                    {i.name}
                    </Typography>
                    </CardContent>
                    </CardActionArea>
        </Card>
            </Item>
            </Link>
          </Grid>
        ))}
        </Grid>
        </Box>
      </main>

      <footer className={styles.footer}>
          <span className={styles.logo}>
            Created by Restiani Andhita Mustikasari
          </span>
      </footer>
    </div>
  )
}

export default withApollo({ssr:true})(Category);
